services:
  mediawiki:
    image: mediawiki:1.43.1-fpm-alpine
    container_name: mediawiki
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=${MEDIAWIKI_DB_HOST}
      - MEDIAWIKI_DB_PORT=${MEDIAWIKI_DB_PORT}
      - MEDIAWIKI_DB_NAME=${MEDIAWIKI_DB_NAME}
      - MEDIAWIKI_DB_USER=${MEDIAWIKI_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${MEDIAWIKI_DB_PASSWORD}
    volumes:
      - ./volumes/mediawiki/extensions:/var/www/html/extensions
      - ./volumes/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - wiki-net
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mariadb/data:/var/lib/mysql
    networks:
      - wiki-net
    restart: unless-stopped


networks:
  wiki-net:
    driver: bridge