services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    ports:
      - "80:80"
      - "2222:22"
    depends_on:
      - mariadb
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=${MEDIAWIKI_DB_HOST}
      - MEDIAWIKI_DB_PORT=${MEDIAWIKI_DB_PORT}
      - MEDIAWIKI_DB_NAME=${MEDIAWIKI_DB_NAME}
      - MEDIAWIKI_DB_USER=${MEDIAWIKI_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${MEDIAWIKI_DB_PASSWORD}
    volumes:
      - ./volumes/mediawiki/images:/var/www/html/images
      - ./volumes/mediawiki/extensions:/var/www/html/extensions
      - ./volumes/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - wiki-net
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "2223:22"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mariadb/data:/var/lib/mysql
    networks:
      - wiki-net
    restart: unless-stopped


  ssh:
    image: linuxserver/openssh-server
    container_name: openssh
    ports:
      - "8222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD_ACCESS=true
      - USER_NAME=wiki
      - USER_PASSWORD=wikipass
    restart: unless-stopped
    platform: linux/arm64/v8

networks:
  wiki-net:
    driver: bridge